### PR TITLE
Fix broken references for link element and secure context

### LINKED ISSUE #56: Broken references in Media Feeds
While crawling [Media Feeds](https://wicg.github.io/media-feeds/), the following links to other specifications were detected as pointing to non-existing anchors, which should be fixed:
* [ ] https://html.spec.whatwg.org/multipage/#link
* [ ] https://www.w3.org/TR/secure-contexts/#secure-context

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

### PR DESCRIPTION
**Pull request by yrw-google**
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/media-feeds/pull/58.html" title="Last updated on Feb 6, 2023, 2:44 AM UTC (18db9b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-feeds/58/540aed1...18db9b3.html" title="Last updated on Feb 6, 2023, 2:44 AM UTC (18db9b3)">Diff</a>

### CODE REVIEW

**Comment by johannhof** [comment]
@dontcallmedom FYI this is still failing IPR checks, anything we can do to help here? :)

**Comment by johannhof** [comment]
("still" as in https://github.com/WICG/media-feeds/pull/55#issuecomment-1183088779)

**Comment by dontcallmedom** [comment]
@deniak can you take a look at the IPR checker set up for this repo? Thanks!

**Comment by deniak** [comment]
The repository manage was not properly updated after the rename of the repo from `media-feeds-api` to `media-feeds`. I've fixed the record to unblock the PR and I'll investigate what caused the issue.

**Review by johannhof — APPROVED** [review]
Thanks!

**Pull request merged**
